package com.example.myapplication;


import android.app.AlertDialog;
import android.content.DialogInterface;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatDialogFragment;

public class Dialog extends AppCompatDialogFragment {



    MainActivity mainActivity = new MainActivity();

    @NonNull
    @Override
    public android.app.Dialog onCreateDialog(@Nullable Bundle savedInstanceState) {


        final String[] sort = {"Металлы", "Шелочные металлы", "Щелочно-земельные металлы","Лантаноиды","Актоноиды","Переходные металлы","Пост-переходные металлы",
        "Полуметаллы","Неметаллы","Благородные газы"};



        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        builder.setTitle("Выберите нужный вам вариант")
                .setItems(sort, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {
                        switch (which){
                            case 0:
                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);  	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);  	((MainActivity) getActivity()).btn_3.setAlpha((float) 1.00);  	((MainActivity) getActivity()).btn_4.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_5.setAlpha((float) 0.25);  	((MainActivity) getActivity()).btn_6.setAlpha((float) 0.25);  	((MainActivity) getActivity()).btn_7.setAlpha((float) 0.25);  	((MainActivity) getActivity()).btn_8.setAlpha((float) 0.25);  	((MainActivity) getActivity()).btn_9.setAlpha((float) 0.25);  	((MainActivity) getActivity()).btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_12.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_13.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_19.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_20.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_22.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_23.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_24.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_25.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_26.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_27.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_28.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_29.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_30.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_32.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_37.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_38.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_39.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_40.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_42.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_43.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_44.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_45.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_46.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_47.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_48.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_49.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_50.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_52.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_56.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_57.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_58.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_59.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_60.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_62.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_63.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_64.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_65.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_66.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_67.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_68.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_69.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_70.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_72.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_73.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_74.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_75.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_76.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_77.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_78.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_79.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_80.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_82.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_83.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_84.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25); 	((MainActivity) getActivity()).btn_87.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_88.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_89.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_90.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_92.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_93.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_94.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_95.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_96.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_97.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_98.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_99.setAlpha((float) 1.00); 	((MainActivity) getActivity()).btn_100.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_102.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_103.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_104.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_105.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_106.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_107.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_108.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);

                                break;
                            case 1:

                                ((MainActivity) getActivity()). btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_32.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_52.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);


                                break;
                            case 2:


                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_5.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_32.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_52.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);


                                break;
                            case 3:

                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_32.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_52.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_58.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_59.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_60.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_62.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_63.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_64.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_65.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_66.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_67.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_68.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_69.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_70.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);


                                break;
                            case 4:

                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_32.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_52.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_90.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_92.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_93.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_94.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_95.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_96.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_97.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_98.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_99.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_100.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_102.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_103.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);


                                break;
                            case 5:

                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_22.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_23.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_24.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_25.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_26.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_27.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_28.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_29.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_30.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_32.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_40.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_42.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_43.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_44.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_45.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_46.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_47.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_48.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_52.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_72.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_73.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_74.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_75.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_76.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_77.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_78.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_79.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_80.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_105.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_106.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_107.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_108.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_109.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_110.setAlpha((float)1.00);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_112.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);



                                break;
                            case 6:


                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_32.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_50.setAlpha((float) 1.00);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_52.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_82.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_83.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_84.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);



                                break;
                            case 7:


                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_32.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_33.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_52.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);



                                break;
                            case 8:


                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_6.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_7.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_8.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_9.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_15.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_16.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_17.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_32.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_33.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_34.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_35.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_52.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_53.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);



                                break;
                            case 9:


                                ((MainActivity) getActivity()).btn_1.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_2.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_3.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_4.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_5.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_6.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_7.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_8.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_9.setAlpha((float) 1.00);	((MainActivity) getActivity()). btn_10.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_11.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_12.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_13.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_14.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_15.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_16.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_17.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_18.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_19.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_20.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_21.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_22.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_23.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_24.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_25.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_26.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_27.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_28.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_29.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_30.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_31.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_32.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_33.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_34.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_35.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_36.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_37.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_38.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_39.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_40.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_41.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_42.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_43.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_44.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_45.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_46.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_47.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_48.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_49.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_50.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_51.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_52.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_53.setAlpha((float) 1.00);	((MainActivity) getActivity()).btn_54.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_55.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_56.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_57.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_58.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_59.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_60.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_61.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_62.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_63.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_64.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_65.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_66.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_67.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_68.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_69.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_70.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_71.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_72.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_73.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_74.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_75.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_76.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_77.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_78.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_79.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_80.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_81.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_82.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_83.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_84.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_85.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_86.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_87.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_88.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_89.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_90.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_91.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_92.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_93.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_94.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_95.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_96.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_97.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_98.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_99.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_100.setAlpha((float) 0.25);
                                ((MainActivity) getActivity()).btn_101.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_102.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_103.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_104.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_105.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_106.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_107.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_108.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_109.setAlpha((float) 0.25);	((MainActivity) getActivity()). btn_110.setAlpha((float)0.25);
                                ((MainActivity) getActivity()).btn_111.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_112.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_113.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_114.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_115.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_116.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_117.setAlpha((float) 0.25);	((MainActivity) getActivity()).btn_118.setAlpha((float) 0.25);



                                break;


                            default:
                        }

                    }

                })
        ;
        return builder.create();}
}
